ParadymeIntern/ParadymeIntern/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.auth import views
from RSR.views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^RSR/', include('RSR.urls')),
    url(r'^$', RedirectView.as_view(url='RSR/main/', permanent=True)),
    url(r'^accounts/login/$', views.login, name ='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url('^accounts/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ParadymeIntern/RSR/urls.py
from django.conf.urls import url
from django.contrib import admin
from. import views
from RSR.views import *

app_name = 'RSR'


urlpatterns = [

    url(r'^uploaddoc/$', uploaddoc, name='uploaddoc'),
    url(r'^uploadlist/$', uploadlist, name = 'uploadlist'),
    url(r'^listdelete/$', listdelete, name="listdelete"),
    url(r'^main/$', main, name = 'main'),
    url(r'^search/$', search, name='search'),

    #Edit page
    url(r'^edit/(?P<person_id>\d+)/$', views.person_edit, name='person-edit'),
    url(r'^edit_skill/(?P<skill_id>\d+)/$', views.skill_edit, name='skill-edit'),
    url(r'^edit_company/(?P<company_id>\d+)/$', views.company_edit, name='company-edit'),
    url(r'^edit_school/(?P<school_id>\d+)/$', views.school_edit, name='school-edit'),
    url(r'^edit_course/(?P<course_id>\d+)/$', views.course_edit, name='course-edit'),
    url(r'^edit_language/(?P<language_id>\d+)/$', views.language_edit, name='language-edit'),
    url(r'^edit_sidepro/(?P<sidepro_id>\d+)/$', views.sidepro_edit, name='sidepro-edit'),
    url(r'^edit_award/(?P<award_id>\d+)/$', views.award_edit, name='award-edit'),
    url(r'^edit_club/(?P<club_id>\d+)/$', views.club_edit, name='club-edit'),
    url(r'^edit_volunteer/(?P<volunteer_id>\d+)/$', views.volunteer_edit, name='volunteer-edit'),
    url(r'^edit_professional/(?P<pro_id>\d+)/$', views.professional_edit, name='professional-edit'),
    url(r'^edit_clearance/(?P<clearance_id>\d+)/$', views.clearance_edit, name='clearance-edit'),

    #Delete
    url(r'^delete_skill/(?P<pk>\d+)$', views.skill_delete, name="skill-delete"),
    url(r'^delete_company/(?P<pk>\d+)/$', views.company_delete, name="company-delete"),
    url(r'^delete_school/(?P<pk>\d+)/$', views.school_delete, name="school-delete"),
    url(r'^delete_course/(?P<pk>\d+)/$', views.course_delete, name="course-delete"),
    url(r'^delete_language/(?P<pk>\d+)/$', views.language_delete, name='language-delete'),
    url(r'^delete_sidepro/(?P<pk>\d+)/$', views.sidepro_delete, name='sidepro-delete'),
    url(r'^delete_award/(?P<pk>\d+)/$', views.award_delete, name='award-delete'),
    url(r'^delete_club/(?P<pk>\d+)/$', views.club_delete, name='club-delete'),
    url(r'^delete_volunteer/(?P<pk>\d+)/$', views.volunteer_delete, name='volunteer-delete'),
    url(r'^delete_professional/(?P<pk>\d+)/$', views.professional_delete, name='professional-delete'),

    #ocr search
    url(r'^resumesearch',OCRSearch, name='ocrsearch'),


    url(r'^logout/$', views.logout_page, name = 'logout'),
    url(r'^search/person_detail/(?P<pk>[0-9]+)/$', views.detail, name='detail'),

        #url for autocomplete function for ProfessionalDevelopment class
    url(r'^search/ProfessionalDevelopment-autocomplete/$', ProfessionalDevelopmentAutocomplete.as_view(),
        name='ProfessionalDevelopment-autocomplete',),
        #url for autocomplete function for skills class
    url(r'^search/Skills-autocomplete/$', Skillsutocomplete.as_view(),
        name='Skills-autocomplete',),
        #url for autocomplete function for Volunteering class
    url(r'^search/Volunteering-autocomplete/$', Volunteeringautocomplete.as_view(),
        name='Volunteering-autocomplete',),
        #url for autocomplete function for search bar
    url(r'^search/SearchBar-autocomplete/$', SearchBarautocomplete.as_view(),
        name='SearchBar-autocomplete',),
        #url for autocomplete function for LanguageSpoken class
    url(r'^search/Language-autocomplete/$', Languageautocomplete.as_view(),
        name='LanguageSpoken-autocomplete',),
        #url for autocomplete function for Company class
    url(r'^search/Company-autocomplete/$', Companyautocomplete.as_view(),
        name='Company-autocomplete',)


]

ParadymeIntern/RSR/views.py
# -*- coding: utf-8 -*-
from .models import *
import docx2txt
from django.utils import timezone

# Create your views here.
#=======
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.forms import ModelForm

from RSR.models import *
from RSR.forms import *
from django.shortcuts import get_object_or_404
from django.contrib.auth import logout
from .filters import *
###Search #
from django.db.models import Q
from RSR.persondetails import Detail
from RSR.persondetails2 import Detail2
from django.views.generic.edit import UpdateView
from dal import autocomplete


### json Parsing ##
import json

###TESTING OCR

from PIL import Image
from wand.image import Image as IMG
import pytesseract
import textract

### Limit group###

from django.contrib.auth.decorators import user_passes_test



@user_passes_test(lambda u: u.groups.filter(name='RSR').exists())

def logout_page(request):
    logout(request)
    return HttpResponseRedirect('/')

@login_required
def main(request):
    return render(request, 'main.html')


def get_string(name):
    img=Image.open(name)
    utf8_text = pytesseract.image_to_string(img)
    utf8_text = str(utf8_text.encode('ascii', 'ignore'))
    return utf8_text


@login_required
@user_passes_test(lambda u: u.groups.filter(name='RSR').exists())
def uploaddoc(request):
    # Handle file upload


    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            #### PARSING TEAM = AT THE END OF THE NEXT LINES, USE
            #### temp_doc.wordstr TO GRAB STRING ####


            temp_doc = Document(docfile=request.FILES['docfile'])

            #temp_doc.firstname = Document(docfile=request.POST.get('firstname'))
            #temp_doc.lastname = Document(docfile=request.POST.get('lastname'))
            #temp_doc.type = Document(docfile=request.POST.get('type'))
            temp_doc.firstname = request.POST['firstname']
            temp_doc.lastname = request.POST['lastname']
            temp_doc.type = request.POST['type']
            temp_doc.uploaduser = request.user.username

            temp_doc.save()

            if ".doc" in temp_doc.docfile.path:
                print (temp_doc.docfile.path)
                temp_doc.wordstr = parse_word_file(temp_doc.docfile.path)
                print (temp_doc.wordstr)
                temp_doc.save(update_fields=['wordstr'])

            ### UNCOMMENT THESE LINES FOR MAC/LINUX USERS: OCR/TEXTRACT

            else:

                temp_doc.wordstr = textract.process(temp_doc.docfile.path)

                if len(temp_doc.wordstr) < 50:
                    img=IMG(filename=temp_doc.docfile.path,resolution=200)

                    img.save(filename='temp.jpg')
                    utf8_text = get_string('temp.jpg')
                    os.remove('temp.jpg')

                    print (utf8_text)
                    temp_doc.wordstr = utf8_text
                    temp_doc.save(update_fields=['wordstr'])

                print (temp_doc.wordstr)
                temp_doc.save(update_fields=['wordstr'])

            '''
            ============ PARSING TEAM =====================
            FROM HERE YOU CAN CALL temp_doc.wordstr HERE TO GRAB STRING

            ===============================================
            '''
            ###



            #json testing#
            #check for json file, wont be needed as parsing will return json#


            #========== PARSING TEAM JSON =========== #
            ## GET RID OF THIS LINE BELOW
            ## replace with below line:  (just so we dont have to redo indents)
            #if True:
            # ======================================#


            if ".json" in temp_doc.docfile.path:



                #either load json, or recieve json file

                ### ===================== ######
                #PARSING, REPLACE temp_doc.docfile.path with the json path!!
                ### ====================== ######
                js = json.load(open(temp_doc.docfile.path))


                #iterate through json file

                #initialize person out side of for loop/if statements so we can use it later
                p_name = temp_doc.firstname + " " + temp_doc.lastname
                person = Person(Name=p_name)
                for label in js:

                    #Checking Labels to see which table to create
                    if label == "person":
                        for key in js[label]:
                            #if key == "name":
                            #    person.Name = js[label][key]
                            if key == "email":
                                person.Email = js[label][key]
                            elif key == "address":
                                person.Address = js[label][key]
                            elif key == "zipcode":
                                person.ZipCode = js[label][key]
                            elif key == "state":
                                person.State = js[label][key]
                            elif key == "phone":
                                person.PhoneNumber = js[label][key]
                            elif key == "linkedin":
                                person.Linkedin = js[label][key]
                            elif key == "github":
                                person.GitHub = js[label][key]
                        person.Resume = temp_doc.docfile
                        person.TypeResume = temp_doc.type
                        person.save()


                    elif label == "skills":
                        for key in js[label]:
                            #check to see if skill exists
                            query_set=Skills.objects.all()
                            query_set=query_set.filter(Name=key["skill"])
                            #if skill does not exist create skill
                            if not query_set:
                                query_set = Skills(Name = key["skill"])
                                query_set.save()
                            #if skill does exist, grab first match from queryset
                            else:
                                query_set = query_set[0]
                            skill_to_person = PersonToSkills(SkillsID = query_set, PersonID = person,YearsOfExperience = key["YearsOfExperience"])
                            skill_to_person.save()

                    elif label == "work":
                        for key in js[label]:
                            #check to see if company exists
                            query_set=Company.objects.all()
                            query_set=query_set.filter(Name=key["company"])
                            #if company does not exist create skill
                            if not query_set:
                                query_set = Company(Name = key["company"])
                                query_set.save()
                            #if company does exist, grab first match from queryset
                            else:
                                query_set = query_set[0]
                            #intermediary table stuff
                            company_to_person = PersonToCompany(CompanyID = query_set, PersonID = person,
                                Title = key["title"],
                                ExperienceOnJob = key["experience"],
                                StartDate = key["startDate"],
                                EndDate = key["endDate"],
                                Desc = key["summary"])
                            company_to_person.save()

                    elif label == "education":
                        for key in js[label]:
                            #check to see if School exists
                            query_set=School.objects.all()
                            query_set=query_set.filter(Name=key["school"]["name"]).filter(DegreeLevel = key["school"]["degreeLevel"])
                            #if School does not exist create skill
                            if not query_set:
                                query_set = School(Name = key["school"]["name"], DegreeLevel = key["school"]["degreeLevel"])
                                query_set.save()
                            #if School does exist, grab first match from queryset
                            else:
                                query_set = query_set[0]

                            # NOW DO MAJOR
                            query_set_1=Major.objects.all()
                            query_set_1=query_set_1.filter(Name=key["major"]["major"]).filter(Dept__icontains = key["major"]["dept"]).filter(MajorMinor__icontains = key["major"]["major/minor"])
                            if not query_set_1:
                                query_set_1 = Major(Name = key["major"]["major"], Dept = key["major"]["dept"], MajorMinor = key["major"]["major/minor"])
                                query_set_1.save()
                            #if School does exist, grab first match from queryset
                            else:
                                query_set_1 = query_set_1[0]

                            #intermediary table stuff
                            ed_to_person = PersonToSchool(SchoolID = query_set, PersonID = person, MajorID = query_set_1,
                                GPA = key["GPA"],
                                GradDate = key["gradDate"])
                            ed_to_person.save()


                    elif label == "sideprojects":

ParadymeIntern/RSR/templates/acc_cont.html
{% extends 'navigation.html' %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <h2 style = " text-decoration: underline;text-decoration-color: orange;font-family: 'Open Sans', Helvetica, Arial, sans-serif;">User Access Control</h2>

    </div>
</div>
  {% endblock %}

ParadymeIntern/RSR/templates/award_update_form.html
{% extends 'navigation.html' %}
{% load widget_tweaks %}
{% block content %}
<!--ADD THIS DIV CLASS TO ALL-->
<div class="container content-section text-center">

<div style="color:#000">
	<h3 style = "color:#FFF"> Editing {{person.PersonID.Name}}'s Award Info</h3>
	<br/>
    <form method="POST" class="post-form">{% csrf_token %}
	    {% for field in form %}
			<div style= "color:#FFF">{{field.label_tag}}</div> {% render_field field class="form-control" style=" width: 300px; margin:auto;" %}
		{% endfor %}
		<br/>
        <button type="submit" class="save btn btn-default">Save</button>

    </form>
	<!--delete -->
		</p>
		<form action="{% url 'RSR:award-delete' pk %}" method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                 <input onclick="return confirm('Are you sure you want to delete this award?')" class = "btn btn-default btn-file" type="submit" value="Delete" />
             </form>

</div>
	{% endblock %}

ParadymeIntern/RSR/templates/clearance_update_form.html
{% extends 'navigation.html' %}
{% load widget_tweaks %}
{% block content %}
<!--ADD THIS DIV CLASS TO ALL-->
<div class="container content-section text-center">

<div style="color:#000">
	<h3 style = "color:#FFF"> Editing {{person.PersonID.Name}}'s Clearance Info</h3>
	<br/>
    <form method="POST" class="post-form">{% csrf_token %}
	    {% for field in form %}
			<div style= "color:#FFF">{{field.label_tag}}</div> {% render_field field class="form-control" style=" width: 300px; margin:auto;" %}
		{% endfor %}
		<br/>
        <button type="submit" class="save btn btn-default">Save</button>

    </form>
</div>
{% endblock %}

ParadymeIntern/RSR/templates/club_update_form.html
{% extends 'navigation.html' %}
{% load widget_tweaks %}
{% block content %}
<!--ADD THIS DIV CLASS TO ALL-->
<div class="container content-section text-center">

<div style="color:#000">
	<h3 style = "color:#FFF"> Editing {{person.PersonID.Name}}'s Clubs & Hobbies Info</h3>
	<br/>
    <form method="POST" class="post-form">{% csrf_token %}
	    {% for field in form %}
			<div style= "color:#FFF">{{field.label_tag}}</div> {% render_field field class="form-control" style=" width: 300px; margin:auto;" %}
		{% endfor %}
		<br/>
        <button type="submit" class="save btn btn-default">Save</button>

    </form>
	<!--delete --></p>
		<form action="{% url 'RSR:club-delete' pk %}" method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                 <input onclick="return confirm('Are you sure you want to delete this club?')" class = "btn btn-default btn-file" type="submit" value="Delete" />
		</form>

</div>

{% endblock %}

ParadymeIntern/RSR/templates/company_update_form.html
{% extends 'navigation.html' %}
{% load widget_tweaks %}
{% block content %}
<!--ADD THIS DIV CLASS TO ALL-->
<div class="container content-section text-center">

<div style="color:#000">
	<h3 style = "color:#FFF"> Editing {{person.PersonID.Name}}'s Work History Info</h3>
	<br/>
    <form method="POST" class="post-form">{% csrf_token %}
	    {% for field in form %}
			<div style= "color:#FFF">{{field.label_tag}}</div> {% render_field field class="form-control" style=" width: 300px; margin:auto;" %}
		{% endfor %}
		<br/>
        <button type="submit" class="save btn btn-default">Save</button>

    </form>
	<!--delete --></p>
			<form action="{% url 'RSR:company-delete' pk %}" method="post">
                 {% csrf_token %}
                 <input onclick="return confirm('Are you sure you want to delete this history?')" class = "btn btn-default btn-file" type="submit" value="Delete" />
             </form>
</div>

{% endblock %}

ParadymeIntern/RSR/templates/course_update_form.html
{% extends 'navigation.html' %}
{% load widget_tweaks %}
{% block content %}
<!--ADD THIS DIV CLASS TO ALL-->
<div class="container content-section text-center">

<div style="color:#000">
	<h3 style = "color:#FFF"> Editing {{person.PersonID.Name}}'s Courses Info</h3>
	<br/>
    <form method="POST" class="post-form">{% csrf_token %}
	    {% for field in form %}
			<div style= "color:#FFF">{{field.label_tag}}</div> {% render_field field class="form-control" style=" width: 300px; margin:auto;" %}
		{% endfor %}
		<br/>
        <button type="submit" class="save btn btn-default">Save</button>

    </form>
	</p><form action="{% url 'RSR:course-delete' pk %}" method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                 <input onclick="return confirm('Are you sure you want to delete this course?')" class = "btn btn-default btn-file" type="submit" value="Delete" />
     </form>
</div>

{% endblock %}

ParadymeIntern/RSR/templates/export.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Export</title>
</head>
<body>
    <p>
        <a href = "" >Export</a>
    </p>
</body>
</html>

ParadymeIntern/RSR/templates/main.html
                   {%load static%}
                   <!DOCTYPE html>
                   <html lang="en">
                   <style>
                   @import url(https://fonts.googleapis.com/css?family=Raleway:100,400,700);
                   .TextBox{
                     -moz-border-radius:1px;
                     -webkit-border-radius:1px;
                     border-radius:1px;
                     border: #solid 10px #000;
                     background-color: rgba(255,255,255,0.7);
                     padding-top: 35px;
                     padding-bottom: 15px;
                     height:100%;
                     width:100%;
                     margin-left: auto ;
                     margin-right: auto ;
                   }

                   </style>
                   <head>

                       <meta charset="utf-8">
                       <meta http-equiv="X-UA-Compatible" content="IE=edge">
                       <meta name="viewport" content="width=device-width, initial-scale=1">
                       <meta name="description" content="">
                       <meta name="author" content="">

                       <title >RSR</title>

                       <!-- Bootstrap Core CSS -->
                       <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

                       <!-- Custom Fonts -->
                       <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
                       <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
                       <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

                       <!-- Theme CSS -->
                       <link href="{% static 'css/grayscale.min.css' %}" rel="stylesheet">

                       <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
                       <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
                       <!--[if lt IE 9]>
                           <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
                           <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
                       <![endif]-->

                   </head>

                   <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

                       <!-- Navigation -->
                       <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
                           <div class="container">
                               <div class="navbar-header">
                                   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                                       Menu <i class="fa fa-bars"></i>
                                   </button>
                                   <a class="navbar-brand page-scroll" href="#page-top">
                                       <img style = "width: auto; height: 25px;" src = "http://www.paradymemanagement.com/wp-content/uploads/2015/11/paradyme-green.png">
                                   </a>
                               </div>

                               <!-- Collect the nav links, forms, and other content for toggling -->
                               <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                                   <ul class="nav navbar-nav">
                                       <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                                       <li class="hidden">
                                           <a href="#page-top"></a>
                                       </li>
                                       <li>
                                           <a href="{% url 'RSR:uploaddoc' %}" >Upload</a>
                                       </li>
                                       <li>
                                           <a href="{% url 'RSR:search' %}">Search</a>
                                       </li>
                                       <li>
                    <a href="{% url 'RSR:ocrsearch' %}">Resume Regex</a>
                </li>
                                    
                                       <li>
                                           <a href="{% url 'logout' %}">Log Out</a>
                                       </li>
                                   </ul>
                               </div>
                               <!-- /.navbar-collapse -->
                           </div>
                           <!-- /.container -->
                       </nav>

                       <!-- Intro Header -->
                       <header class="intro">
                           <div class="intro-body">
                               <div class="container">
                                   <div class="row">
                                       <div class="col-md-8 col-md-offset-2">
                                         <div class="TextBox">
                                           <h2 style = "color: #262626; font-family: Raleway, Open Sans  , Arial, sans-serif;text-decoration: underline;text-decoration-color: orange;"class="brand-heading">RSR</h2>
                                           <h4 style = "font-weight: normal;color: #666666; font-family:  Open Sans  , Arial, sans-serif;">Resume Parser and Skills Repository</h4>
                                         </div>
                                           <a href="#about" class="btn btn-circle page-scroll">
                                               <i class="fa fa-angle-double-down animated"></i>
                                           </a>

                                       </div>
                                   </div>
                               </div>
                           </div>
                       </header>

                       <!-- About Section -->
                       <section id="about" class="container content-section text-center">
                           <div class="row">
                               <div class="col-lg-8 col-lg-offset-2">
                                   <h2 style = " text-decoration: underline;text-decoration-color: orange;font-family: Raleway, 'Open Sans', Helvetica, Arial, sans-serif;">About RSR</h2>
                                   <p>Use this place if needed for an about. </p>
                                   <p>Here too, maybe a user guide</p>
                                   <p>Continued.</p>
                               </div>
                           </div>
                       </section>



                       <!-- Footer -->
                       <footer>
                           <div class="container text-center">
                               <p>Copyright &copy; Paradyme Management 2017</p>
                           </div>
                       </footer>

                       <!-- jQuery -->
                       <script src="{% static 'vendor/jquery/jquery.js' %}"></script>

                       <!-- Bootstrap Core JavaScript -->
                       <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

                       <!-- Plugin JavaScript -->
                       <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

                       <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
                       <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

                       <!-- Theme JavaScript -->
                       <script src="{% static 'js/grayscale.min.js' %}"></script>

                   </body>

                   </html>

ParadymeIntern/RSR/templates/ocr.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OCR</title>
</head>
<body>

    <p>
        <a href = "" >OCR</a>
    </p>

</body>
</html>

ParadymeIntern/RSR/templates/person_update_form.html
{% extends 'navigation.html' %}
{% load widget_tweaks %}
{% block content %}
<!--ADD THIS DIV CLASS TO ALL-->
<div class="container content-section text-center">


<div style="color:#000">
	<h3 style = "color:#FFF"> Editing {{person.Name}}'s Personal Info</h3>
	<br/>
    <form method="POST" class="post-form">{% csrf_token %}
		{% for field in form %}
			<div style= "color:#FFF">{{field.label_tag}}</div> {% render_field field class="form-control" style=" width: 300px; margin:auto;" %}
		{% endfor %}
		<br/>
		<button type="submit" class = "button-style">Edit</button>

 </form>

<!-- DONT FORGET TO CLOSE DIV-->
 </div>
{% endblock %}

ParadymeIntern/RSR/templates/professional_update_form.html
{% extends 'navigation.html' %}
{% load widget_tweaks %}
{% block content %}
<!--ADD THIS DIV CLASS TO ALL-->
<div class="container content-section text-center">

<div style="color:#000">
	<h3 style = "color:#FFF"> Editing {{person.PersonID.Name}}'s Professional Development Info</h3>
	<br/>
    <form method="POST" class="post-form">{% csrf_token %}
	    {% for field in form %}
			<div style= "color:#FFF">{{field.label_tag}}</div> {% render_field field class="form-control" style=" width: 300px; margin:auto;" %}
		{% endfor %}
		<br/>
        <button type="submit" class="save btn btn-default">Save</button>

    </form>
	</p><form action="{% url 'RSR:professional-delete' pk %}" method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                 <input onclick="return confirm('Are you sure you want to delete this professional development?')" class = "btn btn-default btn-file" type="submit" value="Delete" />
             </form>
</div>

{% endblock %}

ParadymeIntern/RSR/templates/search.html
{% extends 'navigation.html' %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <h2 style = " text-decoration: underline;text-decoration-color: orange;font-family: 'Open Sans', Helvetica, Arial, sans-serif;">Search / Export</h2>

    </div>
</div>
  {% endblock %}

ParadymeIntern/RSR/templates/sidepro_update_form.html
{% extends 'navigation.html' %}
{% load widget_tweaks %}
{% block content %}
<!--ADD THIS DIV CLASS TO ALL-->
<div class="container content-section text-center">

<div style="color:#000">
		<h3 style = "color:#FFF"> Editing {{person.PersonID.Name}}'s Side Project Info</h3>
	<br/>
    <form method="POST" class="post-form">{% csrf_token %}
	    {% for field in form %}
			<div style= "color:#FFF">{{field.label_tag}}</div> {% render_field field class="form-control" style=" width: 300px; margin:auto;" %}
		{% endfor %}
		<br/>
        <button type="submit" class="save btn btn-default">Save</button>

    </form>
	 </p><form action="{% url 'RSR:sidepro-delete' pk %}" method="post" enctype="multipart/form-data">
                 {% csrf_token %}
                 <input onclick="return confirm('Are you sure you want to delete this side project?')" class = "btn btn-default btn-file" type="submit" value="Delete" />
     </form>
</div>

{% endblock %}